### ISSUE TITLE
Standardise order of imports

### ISSUE THREAD

**Issue by matthewpratt13** [silversixpence-crypto/dapol#114]
It's a good idea to keep the import formats and ordering consistent – i.e., what to import and how to group them. I also noticed that there are some imports within a function, which is not best practice to my knowledge

**Comment by Stentonian** [comment]
> which is not best practice to my knowledge
I copied this pattern from the std library. I like how you can isolate imports to code blocks to make it clear that the import is not used anywhere else.

**Comment by matthewpratt13** [comment]
Fair enough. Makes sense since this is a library

**Comment by Stentonian** [comment]
Note that the executable does not change depending on where `use` statements are placed: https://users.rust-lang.org/t/use-statements-inside-functions/44798/6
