### ISSUE TITLE
Fully implement `From` where needed

### ISSUE THREAD

**Issue by matthewpratt13** [silversixpence-crypto/dapol#115]
I noticed that a number of objects have a `from()` method, which is used on creation. This method typically refers to conversion more than construction, but I can see the crossover. Fully implementing the `From` trait (i.e. `impl From<T> for U`) makes it clear that it is a conversion, and offers additional methods such as `into()` and `as_ref()` for free.

If the actual intention is to construct, then you should use `new() -> Self`

`new()` should also always never return anything other than `Self` (i.e., it should not return a `Result` or `Option`). In those cases, use `build()`

**Comment by Stentonian** [comment]
Thanks for the advice, will definitely make sure to do this

**Comment by Stentonian** [comment]
https://rust-lang.github.io/api-guidelines/interoperability.html#c-conv-traits

https://rust-lang.github.io/api-guidelines/predictability.html#c-ctor

**Comment by Stentonian** [comment]
Since implementing `From` gives `.into()`, and `into_: owned -> owned (non-Copy types)` ([ref](https://rust-lang.github.io/api-guidelines/naming.html#c-conv)) it seems that if the type param for `From` is a reference (`From<&T>`) then we should rather do a `new(x: &T)` function.
