### ISSUE TITLE
Standardise individual file layout

### ISSUE THREAD

**Issue by matthewpratt13** [silversixpence-crypto/dapol#116]
It's a good idea to have consistency across how the files are structured. I.e., the order of imports, objects, implementation blocks and internal functions.

Generally implementation blocks go just underneath the object to which they apply, with internal functions right at the bottom. 

A good layout is:

```rust
use some_external_import;
use some_local_import;
pub use some_local_import;

mod some_inner_module;
pub use some_inner_module_code_to_reexport;

///////////////////////////////

pub const SOME_CONST: ConstType = <some_compile_time_constant_value>;

///////////////////////////////

trait SomeTrait {
    fn some_required_function() {}
}

///////////////////////////////

enum SomeEnum {}

impl SomeEnum {}

///////////////////////////////

type SomeType = InnerType;

impl SomeType {}

///////////////////////////////

struct T {}

impl T {}

///////////////////////////////

// a good way to structure implementation blocks is as follows:

impl T {
    pub fn new() -> Self {} // constructors

    pub fn some_associated_function() {}

    pub fn some_struct_field(&self) -> &Field {} // getters

    fn some_internal_function() {}
}

impl SomeTrait for T {
    fn some_required_function() {}
}

///////////////////////////////

pub fn some_module_function() {}

///////////////////////////////

mod tests

use super::*;

fn some_test() {}
```

Errors can either go right at the top or at the bottom just above `tests`

**Comment by Stentonian** [comment]
Thanks for the blueprint! IIRC this is the layout I used. There were some exceptions where impl blocks made more sense to live in different files. Can you point to specific cases where this blueprint should be followed but isn't?

**Comment by matthewpratt13** [comment]
I had a look at the code again, and it looks all good. I got lost certain files with multiple sections, where there were enums defined under structs, etc.. I'll close the issue
