### ISSUE TITLE
Cleanup test functions in dapol/mod.rs

### ISSUE THREAD

**Issue by Stentonian** [silversixpence-crypto/dapol#19]
https://github.com/silversixpence-crypto/dapol/blob/ebaa2541ebad993a9ad75e17fd8029e301d45c71/src/dapol/mod.rs#L194

**Comment by ameya-deshmukh** [comment]
@Stentonian in my opinion, we should also add a separate ```tests``` folder for the repo for integration tests, will be maintainable in the future for production.

**Comment by Stentonian** [comment]
Note: *"The purpose of unit tests is to test each unit of code in isolation from the rest of the code to quickly pinpoint where code is and isn’t working as expected. You’ll put unit tests in the src directory in each file with the code that they’re testing. The convention is to create a module named tests in each file to contain the test functions and to annotate the module with cfg(test)."* - The Rust Book

**Comment by Stentonian** [comment]
Going to close this since the tree code was rewritten. The mod.rs code will live in the repo for now in case we want to steal some code from it in the future
