### ISSUE TITLE
Consider renaming `Path` to something like `DapolPath` or `NdmSmtPath`

### ISSUE THREAD

**Issue by matthewpratt13** [silversixpence-crypto/dapol#97]
`Path` is usually assumed to be a struct in the `std::path` module and as such is generally understood as such. (https://doc.rust-lang.org/std/path/index.html)

Renaming this crate's `Path` struct to something like `DapolPath` or `NdmSmtPath` would make it easier to distinguish the two, as they are quite different.

**Comment by Stentonian** [comment]
Has been renamed to `PathSiblings`
